### ISSUE TITLE
Start the project

### ISSUE THREAD

**Issue by bcsamrudh** [Sanjayrk0206/Smart-Attendance#1]
@Sanjayrk0206 
I think we should start building the project.

**Comment by Sanjayrk0206** [comment]
@bcsamrudh 
We will. Currently, I am going through the proposal as there are many. Once it's done, we will have a meet and discuss on that workflow.

**Comment by bcsamrudh** [comment]
> @bcsamrudh 
> We will. Currently, I am going through the proposal as there are many. Once it's done, we will have a meet and discuss on that workflow.
> 

Ok.
